version: '3'

services:
  api-escuela:
    build: api-escuela
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://api_escuela:3306/api_escuela?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: mysql
    restart: always
    depends_on:
      api_escuela:
          condition: service_healthy
  api_escuela:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: api_escuela
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10