spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql = true
spring.application.name= api-escuela
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.open-in-view = true
spring.jpa.hibernate.ddl-auto= none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug

server.port = 8080